import { FormField, SelectField } from "@/components/form-field";
import { MessageBanner } from "@/components/message-banner";
import { PageHeader } from "@/components/page-header";
import { requireOrganization, requireUser } from "@/core/auth/context";
import { updateOrganization } from "@/core/organizations/actions";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ error?: string; message?: string }> }) {
  const context = await requireOrganization(); const { supabase } = await requireUser();
  const [{ data: roles }, { data: modules }] = await Promise.all([supabase.from("roles").select("id,name,description").eq("organization_id", context.organization.id).order("name"), supabase.from("organization_modules").select("id,module_key,enabled").eq("organization_id", context.organization.id).order("module_key")]); const params = await searchParams;
  return (<><PageHeader title="Organization settings" description="Core organization, access roles, and future module registry." /><MessageBanner error={params.error} message={params.message} /><section className="section-grid"><div className="panel"><h2>Organization</h2><form action={updateOrganization} className="form-grid"><FormField label="Organization name" name="name" defaultValue={context.organization.name} required /><SelectField label="Timezone" name="timezone" defaultValue={context.organization.timezone}><option value="America/New_York">Eastern Time</option><option value="America/Chicago">Central Time</option><option value="America/Denver">Mountain Time</option><option value="America/Los_Angeles">Pacific Time</option><option value="America/Anchorage">Alaska Time</option><option value="Pacific/Honolulu">Hawaii Time</option></SelectField><button className="button" type="submit">Save settings</button></form></div><div className="panel"><h2>Access roles</h2><p className="muted">Capabilities are assigned centrally; application code does not authorize by role name.</p><ul className="list">{roles?.map((role) => <li key={role.id}><strong>{role.name}</strong><br /><span className="muted">{role.description}</span></li>)}</ul></div><div className="panel"><h2>Module registry</h2><p className="muted">Future modules are registered but remain disabled until their roadmap gate is built and reviewed.</p><ul className="list">{modules?.map((module) => <li key={module.id} style={{ display: "flex", justifyContent: "space-between", gap: "1rem" }}><span>{module.module_key.replaceAll("_", " ")}</span><span className={module.enabled ? "status" : "status off"}>{module.enabled ? "Enabled" : "Not built"}</span></li>)}</ul></div></section></>);
}
